# command + alt + R でリクエスト
POST http://localhost:3000/v1/order/payment
Content-Type: application/json

{
  "items": [
    {
      "name": "scrub",
      "amount": 2000,
      "quantity": 2
    },
    {
      "name": "soap",
      "amount": 1500,
      "quantity": 1
    }
  ],
  "currency": "jpy",
  "paymentMethodId": null
}
